spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: 123
    #    driver-class-name: org.postgresql.Driver
    hikari:
      schema: contacts_schema
#logging:
#  level:
#    root: debug
